# Generated by Django 3.0.5 on 2020-05-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200505_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Heartrates',
            new_name='Heartrate',
        ),
    ]
